language: node_js
node_js:
- '8'
- '6'
env:
- NODE_ENV=development
before_script:
- yarn
script:
- yarn test
after_success: npm run report-coverage
deploy:
  provider: npm
  email: scott@scottmebberson.com
  api_key:
    secure: VSpn9XEUmW8mgPcOlubY8+xXGkCNTBuirIlChizwmCHFHO6VteOFpyP/IpXt8vI6qgYA9LoZ6rb0edfxfaJWyvPT5xH1vQypx/zCtSxs6sPwgiG8afhfk+ssAg52LKZAz6Lvw6OGGXcstPcDGgOIhcB//BlpTnR2L9Q9to5sLgI=
  on:
    tags: true
    repo: linzjs/linz
notifications:
  email:
    on_failure: never
    on_success: never
  slack:
    secure: GxIYZXaKRqfqQZ+XWj9LXHMuNfqMUsY9gcA6pm8uWhmjSkiLMWg6B6w0qLfqtCGXxCLYQDQYfJ+7mERGScr+2gDVOUWZ0DVS5DNSar4kGhQUYPskJ4MCZIFwh3ISmQYCFrl3w/rlz77OfchvkfOmOmIAIycwlhe/396Oyz2vsPo=
