name: build
on:
    push:
        branches-ignore:
            - 'main'
        tags:
            - 'v*'
jobs:
    buildLinz:
        name: Build Linz
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install packages
              run: yarn install
            - name: Testing linz
              run: yarn test
              shell: 'script -q -e -c "bash {0}"'
