name: build
on:
    push:
        branches-ignore:
            - 'main'
        tags:
            - 'v*'
jobs:
    environment:
        name: Setup environment
        uses: idearium/actions/.github/workflows/environment.yaml@v1

    buildLinz:
        name: Build Linz
        needs: environment
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup Buildx
              uses: docker/setup-buildx-action@v2
            - name: Build Linz image
              uses: docker/build-push-action@v4
              with:
                  build-args: |
                      CI_ENV=${{ needs.environment.outputs.CI_ENV }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  context: .
                  file: Dockerfile
                  outputs: type=docker,dest=/tmp/linz.tar
                  tags: linz:latest
            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: linz
                  path: /tmp/linz.tar
    testLinz:
        name: Test plant
        needs: [environment, buildLinz]
        runs-on: ubuntu-latest
        steps:
            - name: Setup Buildx
              uses: docker/setup-buildx-action@v2
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: linz
                  path: /tmp
            - name: Load image
              run: |
                  docker load -i /tmp/linz.tar
            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: 4.4
            - name: Testing linz
              run: |
                  docker run --name linz --rm -i -e CI=true -e NODE_ENV=test linz:latest yarn test-app
