name: Deploy docs

on:
    push:
        branches:
            - master
        paths:
            - 'docusaurus/**'

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Test Build
              run: |
                  if [ -e yarn.lock ]; then
                  yarn install --frozen-lockfile
                  elif [ -e package-lock.json ]; then
                  npm ci
                  else
                  npm i
                  fi
                  npm run build
              working-directory: docusaurus
    gh-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
            - name: Add key to allow access to repository
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  cat <<EOT >> ~/.ssh/config
                  Host github.com
                  HostName github.com
                  IdentityFile ~/.ssh/id_rsa
                  EOT
              working-directory: docusaurus
            - name: Release to GitHub Pages
              env:
                  USE_SSH: true
                  GIT_USER: git
              run: |
                  git config --global user.email "actions@gihub.com"
                  git config --global user.name "gh-actions"
                  if [ -e yarn.lock ]; then
                  yarn install --frozen-lockfile
                  elif [ -e package-lock.json ]; then
                  npm ci
                  else
                  npm i
                  fi
                  npx docusaurus deploy
              working-directory: docusaurus
